sudo: required
services:
    - docker

before_install:
    - docker build -t dvaqueiro/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true dvaqueiro/docker-react npm run test -- --coverage
